server:
  port: 8090
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: event-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/v1/event/**
          filters:
            - TokenRelay=
management:
  tracing:
    sampling:
      probability: 1.0
logging:
  level:
    org:
      springframework:
        web: DEBUG