server:
  port: 8090
spring:
  security:
    oauth2:
      resourceserver:
        jwk:
          issuer-uri: http://host.docker.internal:8080/auth/realms/master
          jwk-set-uri: http://host.docker.internal:8080/auth/realms/master/protocol/openid-connect/certs
  application:
    name: api-gateway
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        add-to-simple-url-handler-mapping: true
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:4200"
            allowedHeaders: "*"
            allowedMethods:
              - GET
              - POST
              - DELETE
              - PATCH
              - PUT
      discovery:
        locator:
          enabled: true
      routes:
        - id: event-service
          uri: http://host.docker.internal:8082
          predicates:
            - Path=/api/v1/event/**
        - id: user-service
          uri: http://host.docker.internal:8081
          predicates:
            - Path=/api/v1/user/**
        - id: ticket-service
          uri: http://host.docker.internal:8083
          predicates:
            - Path=/api/v1/ticket/**
          metadata:
            cors:
             allowedOrigins: '*'
             allowedMethods:
               - GET
               - POST
             allowedHeaders: '*'
             maxAge: 30
management:
  tracing:
    sampling:
      probability: 1.0
logging:
  level:
    org:
      springframework:
        web: DEBUG
        security: DEBUG
eureka:
  client:
    service-url:
      defaultZone: http://host.docker.internal:8761/eureka