server:
  port: 8090
spring:
  application:
    name: api-gateway
  security:
    oauth2:
      client:
        registration:
          gateway:
            provider: my-provider
            client-id: my_client
            client-secret: Nxzj03SLu3lSBZ66Q48Q8LP4Vp8Ukm6V
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8090/login/oauth2/code/{registrationId}
            scope:
              - openid
        provider:
          my-provider:
            issuer-uri: http://localhost:8080/auth/realms/event_ticket_system
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: event-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/v1/event/**
          filters:
            - TokenRelay=
management:
  tracing:
    sampling:
      probability: 1.0
logging:
  level:
    org:
      springframework:
        web: DEBUG