server:
  port: 8082
#  servlet:
#    context-path: /api/v1/
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/auth/realms/event_ticket_system
  application:
    name: event-service
  datasource:
    password: postgres
    username: postgres
    url: jdbc:postgresql://localhost:5432/event_ticket_system_event_service
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka