server:
  port: 8082
  servlet:
    context-path: /api/v1/
spring:
  jackson:
    date-format: "yyyy-MM-dd"
    serialization:
      write_dates_as_timestamps: false
  data:
    elasticsearch:
      schema: http
      host: localhost
      port: 9200
  rabbit:
    host: localhost
    username: user
    password: password
  application:
    name: event-service
  datasource:
    password: postgres
    username: postgres
    url: jdbc:postgresql://localhost:5432/event_ticket_system_event_service
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
springdoc:
  swagger-ui:
    path: /api-docs  # Customize the Swagger UI path
  api-docs:
    enabled: true
    path: /api-docs  # Customize the API documentation path