server:
  port: 8082
  servlet:
    context-path: /api/v1/
spring:
  jackson:
    date-format: "yyyy-MM-dd"
    serialization:
      write_dates_as_timestamps: false
  application:
    name: event-service
  datasource:
    password: postgres
    username: postgres
    url: jdbc:postgresql://host.docker.internal:5433/event_ticket_system_event_service
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
eureka:
  client:
    service-url:
      defaultZone: http://host.docker.internal:8761/eureka