spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: kkraken2005@gmail.com
    password: mzovznksfitxzvkq
    protocol: mail.transport.protocol
    protocolType: smtp
    mailDebug: mail.debug
    danekerscode: true
    enable: mail.smtp.starttls.enable

  application:
    name: notification-service
  rabbit:
    host: localhost
    username: user
    password: password
server:
  port: 8118
