spring:
  kafka:
    consumer:
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.ByteArrayDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: "*"
      bootstrap-servers: host.docker.internal:29092
  mail:
    host: smtp.gmail.com
    port: 587
    username: kkraken2005@gmail.com
    password: mzovznksfitxzvkq
    protocol: mail.transport.protocol
    protocolType: smtp
    mailDebug: mail.debug
    danekerscode: true
    enable: mail.smtp.starttls.enable

  application:
    name: notification-service
server:
  port: 8118
