server:
  port: 8083
  servlet:
    context-path: /api/v1/

spring:
  cloud:
    openfeign:
      client:
        config:
          user:
            url: http://localhost:8081/api/v1/user
          event:
            url: http://localhost:8082/api/v1/user
  application:
    name: ticket-service
  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/event_ticket_system_ticket_service
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update


eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka