server:
  port: 8081
  servlet:
    context-path: /api/v1/user/
spring:
  application:
    name: user-service
  datasource:
    password: postgres
    username: postgres
    url: jdbc:postgresql://localhost:5432/event_ticket_system_user_service
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka